# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test/yaml

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureBicepDeployment@1
  inputs:
    azureSubscription: 'Dev Extension Testing'
    bicepFile: 'AzureBicepDeployment/tests/mocks/deploy.bicep'
    parametersFile: 'AzureBicepDeployment/tests/mocks/dev.parameters.json'
    mode: whatIf
  env:
    SYSTEM_ACCESSTOKEN: $(SYSTEM.ACCESSTOKEN) 